### ISSUE TITLE
auto complete / suggestions don't work

### ISSUE THREAD

**Issue by c0ff-prvt** [bajrangCoder/zed-scss#5]
I am not sure if this is the correct repo to report this issue. As mentioned in [this comment](https://github.com/zed-industries/zed/issues/5356#issuecomment-2106296775), the auto-complete/suggestions don't work. I don't know if this is related to Zed or this extension.

If this is the wrong place for the issue, I apologize for that and you can close my issue.

**Comment by bajrangCoder** [comment]
There is no dedicated language server available for SCSS. Therefore, many users suggest using the CSS language server for SCSS. The CSS language server is built into Zed. To enable it for SCSS, simply adjust the settings and add css language server inside scss mode.

**Comment by jk-propeller** [comment]
This makes sense, sry for the issue then^^

Im gonna try to find out how I can configure this in Zed. Did you ajusted the zed settings in this way (if yes can u share the part in config)?

**Comment by jk-propeller** [comment]
Thanks for your work, this sounds great! Especially because I can't get the built-in VS Code CSS language server working in SCSS :/

**Comment by bajrangCoder** [comment]
Yes , it's not working because currently they have removed it.

So you can now only wait for the update to be merged.

**Comment by jk-propeller** [comment]
Thanks for the quick response! Thanks for the info. I'll wait for v0.0.3 of your extension. 👌

Should we leave this issue open until v0.0.3 is out? This may help others with the same issue as me to know what the current state is.

**Comment by jk-propeller** [comment]
Just saw that v0.0.3 is out. That was very soon, thanks for ur work! Its working now, this makes my workday today better^^

**Comment by bajrangCoder** [comment]
> Just saw that v0.0.3 is out. That was very soon, thanks for ur work! Its working now, this makes my workday today better^^

Glad to hear!
Now I'm going to close this issue.

**Comment by marcolaux** [comment]
auto complete also doesn't work for general CSS things while being inside of an `@import`

**Comment by bajrangCoder** [comment]
@marcolaux Yes, it doesn't show completion for external file (I'm working on it)
But it works fine in @include block 👇

https://github.com/bajrangCoder/zed-scss/assets/71929976/0747647b-7848-4fd2-92ec-e4b12e8d65f3
